# Generated by Django 3.1.1 on 2020-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sitemsg',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=25)),
                ('user_msg', models.CharField(max_length=200)),
            ],
        ),
    ]
